appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: M4i7MjGFhg9F35vlqnWMMLM+unyKEbMDrTarDrp69atsnXdtp9i9WD8km7x21ljLql3eVhZ2hbN8EOyB1B9QHNvN9dj9xeqWWW3NE/nNa3xdlXr2gXktDTMJsqyv58qFbpOyxXwLi59H2dvmf9qCU51+TndB1d249Fyyo6bQcHZPe20knu1PXS9tzWb0tUBhvXaF747UG8uzSLJyJwDFUpErAHh+9/EEUBv2IlmKwUAAxYj+bbR8lHK6/Ph5SKReTqHkgSuQTUltgVnq5O+3OInKwxoYVcl7zBJ4C+MwshmAM8JJmLUADJsrN9A3DV3kHtOo0AcKzadmFLuVGiz3OBoMTziw1HbccPbyedWsjKq1FdYpwXsAKtFO+ycRwfY5ZHQ7e4dzKi6gGEunvRGFUPqYqL05jWs2pHtE/Reh3F8Jv3NdczdvFim2ccpMZh3bY4Fj7/sLjrVaemBbUP8JjH+ynniVEK+husYIJx194TGxNBWfK11bnQBt3A6j5Jv1Nw0ELNj/JaSvSjfyTlEiqhQ89qr15EacKDcjS/ygKlP/CTXPFmwsFiwFXyUGMC02p8Ewpt2RYUri/AHge0foOK/C+l7g8DyRSGohI0kROqhx1hcNf1ruaAi2wxB2zj7kSeS3SyaRe3gntVK8SrWH3Js3SsZIBvIvHfiA9SLD35M=}
provider:
  win: azure
